---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bithub.name" . }}-{{ .Values.designDomain.name }}
  labels:
    {{- include "bithub.labels" . | nindent 4 }}
    component: {{ .Values.designDomain.name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bithub.selectorLabels" . | nindent 6 }}
      component: {{ .Values.designDomain.name | quote }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bithub.selectorLabels" . | nindent 8 }}
        component: {{ .Values.designDomain.name | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bithub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: s3fs-cache
          emptyDir: {}
        - name: s3fs-cache-scope
          emptyDir: {}
        - name: s3fs-cache-image
          emptyDir: {}
      initContainers:
        - name: s3fs-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.s3fs.repository }}:{{ .Values.image.s3fs.tag }}"
          imagePullPolicy: {{ .Values.image.s3fs.pullPolicy }}
          args:
            - |
              S3_MOUNT=${AWS_S3_MOUNT:-/opt/s3fs/bucket};
              mkdir -p $S3_MOUNT/$DOMAIN/scope;
              mkdir -p $S3_MOUNT/$DOMAIN/image;
              echo "Caught $SIGNAL! Unmounting ${S3_MOUNT}...";
              fusermount -uz "${S3_MOUNT}";
              s3fs=$(ps -o pid= -o comm= | grep s3fs | sed -E 's/\s*(\d+)\s+.*/\1/g');
              if [ -n "$s3fs" ]; then
                kill -INT "$s3fs";
              fi
          env:
            - name: DOMAIN
              value: {{ .Values.designDomain.name }}
            - name: AWS_S3_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.urlKey }}
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.bucketNameKey }}
            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.accessIdKey }}
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.accessSecretKey }}
          volumeMounts:
            - name: s3fs-cache
              mountPath: /opt/s3fs/bucket
              mountPropagation: Bidirectional
      containers:
        - name: s3fs-sidecar-bitserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.s3fs.repository }}:{{ .Values.image.s3fs.tag }}"
          imagePullPolicy: {{ .Values.image.s3fs.pullPolicy }}
          env:
            - name: DOMAIN
              value: {{ .Values.designDomain.name }}
            - name: AWS_S3_BUCKET_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.bucketNameKey }}
            - name: AWS_S3_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.urlKey }}
            - name: AWS_S3_BUCKET
              value: $(AWS_S3_BUCKET_BASE):/$(DOMAIN)/scope
            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.accessIdKey }}
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.accessSecretKey }}
          volumeMounts:
            - name: s3fs-cache-scope
              mountPath: /opt/s3fs/bucket
              mountPropagation: Bidirectional
        - name: bitserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.bitserver.repository }}:{{ .Values.image.bitserver.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.bitserver.pullPolicy }}
          env:
          - name: SCOPE
            value: {{ .Values.designDomain.name }}
          - name: SCOPE_REMOTES
            value:
              {{- $remotes := list -}}
              {{- range .Values.designDomain.dependencies -}}
              {{- $remotes = append $remotes (printf "%s@https://%s.%s" . . $.Values.gateway.host) -}}
              {{- end -}}
              {{ printf " %s" (join "," $remotes) }}
          ports:
            - name: scope
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: s3fs-cache-scope
              mountPath: /root/data
              mountPropagation: HostToContainer
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: s3fs-sidecar-easyimage
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.s3fs.repository }}:{{ .Values.image.s3fs.tag }}"
          imagePullPolicy: {{ .Values.image.s3fs.pullPolicy }}
          env:
            - name: DOMAIN
              value: {{ .Values.designDomain.name }}
            - name: AWS_S3_BUCKET_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.bucketNameKey }}
            - name: AWS_S3_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.urlKey }}
            - name: AWS_S3_BUCKET
              value: $(AWS_S3_BUCKET_BASE):/$(DOMAIN)/image
            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.accessIdKey }}
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.bucketSecret.name }}
                  key: {{ .Values.bucketSecret.accessSecretKey }}
          volumeMounts:
            - name: s3fs-cache-image
              mountPath: /opt/s3fs/bucket
              mountPropagation: Bidirectional
        - name: easyimage
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.easyimage.repository }}:{{ .Values.image.easyimage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.easyimage.pullPolicy }}
          env:
          - name: todo
            value: todo
          ports:
            - name: image
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: s3fs-cache-image
              mountPath: /opt/s3fs/bucket
              mountPropagation: Bidirectional
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- range .Values.domains }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bithub.name" $ }}-{{ .name }}
  labels:
    {{- include "bithub.labels" $ | nindent 4 }}
    component: {{ .name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "bithub.selectorLabels" $ | nindent 6 }}
      component: {{ .name | quote }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bithub.selectorLabels" $ | nindent 8 }}
        component: {{ .name | quote }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bithub.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: s3fs-cache
          emptyDir: {}
      initContainers:
        - name: s3fs-init
          volumeMounts:
            - name: s3fs-cache
              mountPath: /data
      containers:
        - name: s3fs
          ecurityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.s3fs.repository }}:{{ $.Values.image.s3fs.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.s3fs.pullPolicy }}
          env:
            - name: todo
              value: todo
          volumeMounts:
            - name: s3fs-cache
              mountPath: /data
              mountPropagation: Bidirectional
        - name: bitserver
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.bitserver.repository }}:{{ $.Values.image.bitserver.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.bitserver.pullPolicy }}
          env:
          - name: SCOPE
            value: {{ .name }}
          - name: SCOPE_REMOTES
            value:
              {{- $remotes := list -}}
              {{- range .dependencies -}}
              {{- $remotes = append $remotes (printf "%s@https://%s.%s" . . $.Values.gateway.host) -}}
              {{- end -}}
              {{ printf " %s" (join "," $remotes) }}
          ports:
            - name: scope
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: s3fs-cache
              mountPath: /root/data
              mountPropagation: HostToContainer
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: easyimage
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.easyimage.repository }}:{{ $.Values.image.easyimage.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.easyimage.pullPolicy }}
          env:
          - name: todo
            value: todo
          ports:
            - name: image
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: s3fs-cache
              mountPath: /root/data
              mountPropagation: HostToContainer
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
