apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: ${name}-service
    files:
      - ../../../../../resources/main/micrc.properties

helmGlobals:
  chartHome: ../../helm

helmCharts:
  - name: bithub
    includeCRDs: false
    releaseName: bithub
    version: 0.0.1
    valuesInline:
      podAnnotations:
        sidecar.istio.io/inject: 'true'
