apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../helm

helmCharts:
  - name: bithub
    includeCRDs: false
    releaseName: colibri-bithub
    version: 0.0.1
    valuesInline:
      gateway:
        name: 'it-colibri-gateway'
        host: 'bithub.integration.it.colibrierp.com.br'
      designDomain:
        name: design
        dependencies:
          - security
          - order
      domains:
        - name: security
          dependencies:
            - design
        - name: order
          dependencies:
            - design
      bucket:
        name: bithub-storage
        endpoint: https://oss-cn-chengdu.aliyuncs.com
        secretName: aliyun-secret
        accessIdKey: access-key
        accessSecretKey: secret-key
