apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../helm

helmCharts:
  - name: bithub
    includeCRDs: false
    releaseName: demo-bithub
    version: 0.0.1
    valuesInline:
      gateway:
        name: 'demo-it/it-demo-gateway'
        host: 'bithub.integration.it.demo.com'
      designDomain:
        name: design
        dependencies:
          - security
          - order
      # domains:
      #   - name: security
      #     dependencies:
      #       - design
      #   - name: order
      #     dependencies:
      #       - design
      bucket:
        name: bithub-storage
        endpoint: https://oss-cn-chengdu.aliyuncs.com
        secretName: aliyun-secret
        accessIdKey: access-key
        accessSecretKey: secret-key
      podAnnotations:
        sidecar.istio.io/inject: 'true'
