---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "bithub.fullname" . }}-{{ .Values.designDomain.name }}-scope
  labels:
    {{- include "bithub.labels" . | nindent 4 }}
    component: {{ .Values.designDomain.name | quote }}
spec:
  hosts:
  - {{ .Values.designDomain.name }}.{{ .Values.gateway.host }}
  gateways:
  - {{ .Values.gateway.name  }}
  http:
  - route:
    - destination:
        host: {{ include "bithub.fullname" . }}-{{ .Values.designDomain.name }}
        port:
          number: {{ .Values.service.scope.port }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "bithub.fullname" . }}-{{ .Values.designDomain.name }}-image
  labels:
    {{- include "bithub.labels" . | nindent 4 }}
    component: {{ .Values.designDomain.name | quote }}
spec:
  hosts:
  - image.{{ .Values.designDomain.name }}.{{ .Values.gateway.host }}
  gateways:
  - {{ .Values.gateway.name  }}
  http:
  - route:
    - destination:
        host: {{ include "bithub.fullname" . }}-{{ .Values.designDomain.name }}
        port:
          number: {{ .Values.service.image.port }}

{{- range .Values.domains }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "bithub.fullname" $ }}-{{ .name }}-scope
  labels:
    {{- include "bithub.labels" $ | nindent 4 }}
    component: {{ .name | quote }}
spec:
  hosts:
  - {{ .name }}.{{ $.Values.gateway.host }}
  gateways:
  - {{ $.Values.gateway.name  }}
  tcp:
  - route:
    - destination:
        host: {{ include "bithub.fullname" $ }}-{{ .name }}
        port:
          number: {{ .Values.service.scope.port }}

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "bithub.fullname" $ }}-{{ .name }}-image
  labels:
    {{- include "bithub.labels" $ | nindent 4 }}
    component: {{ .name | quote }}
spec:
  hosts:
  - image.{{ .name }}.{{ $.Values.gateway.host }}
  gateways:
  - {{ $.Values.gateway.name  }}
  tcp:
  - route:
    - destination:
        host: {{ include "bithub.fullname" $ }}-{{ .name }}
        port:
          number: {{ .Values.service.image.port }}

{{- end }}
